name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Clear cache
      run: |
        sudo rm -rf $HOME/.rvm/gems     # Remove RVM gems cache
        sudo rm -rf $HOME/.bundle       # Remove Bundler cache
    - name: Redis Server
      uses: supercharge/redis-github-action@1.7.0
    - name: Bundle install
      run: |
        bundle install --full-index --redownload
    - name: Run the default task
      run: bundle exec rake
    - name: Run tests
      run: ruby -Itest -e 'ARGV.each { |f| require "./#{f}" if File.file?(f) }' test/**/test_*.rb
